- src/entity/common/Enums.ts
- src/entity/member.entity.ts
- src/entity/post-scrap.entity.ts
- src/entity/post-view.entity.ts
- src/entity/post.entity.ts
- src/entity/team-invite.entity.ts
- src/entity/team-member.entity.ts
entity 추가 매핑
1분
필요한 entity들을 추가로 매핑하였습니다.
> entity 추가 매핑

- src/common/pagination/page-meta.ts
- src/common/pagination/pagination-request.ts
- src/common/pagination/pagination-response.ts
- src/common/pagination/pagination.decorator.ts
- src/common/pagination/pagination.enum.ts
- src/controller/post-management.controller.ts
- src/controller/post-team-member.controller.ts
- src/dto/get-post-apply.dto.ts
- src/dto/get-post-team-member.dto.ts
- src/dto/response/post-apply.response.ts
- src/dto/response/post-team-member.response.ts
- src/repository/team-member.query-repository.ts
- src/service/post-management.service.ts
- src/service/post-team-member.service.ts
페이지네이션 객체 추가
5분
- 페이지네이션 객체 추가
- request, response, meta, decorator
- 스터디 신청자 목록 api에 pagination 적용
- 스터디/프로젝트 멤버 목록 api에 pagination 적용
> Feat: 페이지네이션 객체 추가

- frontend/src/pages/auth/google/redirect/index.tsx
- frontend/src/pages/index.tsx
- src/app.module.ts
- src/common/roles/roles.decorator.ts
- src/controller/app.controller.ts
- src/controller/google-auth.controller.ts
- src/guard/roles.guard.ts
- src/main.ts
RolesGuard 구현
3분
Controller에 RolesGuard 넣어두고, 인증이 필요 없는 곳에 Roles('anyone') 걸어두면 될 것 같습니다. 
밑에 예제도 적어뒀어요.
> RolesGuard 구현

- src/dto/get-post-apply.dto.ts
- src/dto/get-post-team-member.dto.ts
- src/dto/response/post-apply.response.ts
- src/dto/response/post-team-member.response.ts
- src/repository/team-member.query-repository.ts
> Feat: 신청자 목록, 현재 팀원 목록에 포지션 추가

- frontend/src/pages/auth/google/redirect/index.tsx
- src/app.module.ts
- src/controller/member.controller.ts
- src/controller/my-page.controller.ts
- src/dto/request/my-page/patch-my-page-info.dto.ts
- src/dto/response/get-member-info-summary.response.ts
- src/dto/response/member/get-member-info-summary.response.ts
- src/dto/response/my-page/get-my-page-info.response.ts
- src/entity/member.entity.ts
- src/repository/member.query-repository.ts
- src/repository/my-page.query-repository.ts
- src/service/member.service.ts
- src/service/my-page.service.ts
유저 정보 요약 / 마이 페이지 유저 정보 / 마이 페이지 유저 정보 수정 api 추가
3분
> 유저 정보 요약 / 마이 페이지 유저 정보 / 마이 페이지 유저 정보 수정 api 추가

- src/app.module.ts
- src/controller/my-page.controller.ts
- src/dto/response/my-page/get-my-page-scrap.response.ts
- src/entity/post.entity.ts
- src/repository/my-page.query-repository.ts
- src/service/my-page.service.ts
> Feat: 마이 페이지 스크랩 목록 api 구현

- src/controller/my-page.controller.ts
- src/dto/response/my-page/get-my-page-invite.response.ts
- src/entity/common/Enums.ts
- src/repository/my-page.query-repository.ts
- src/service/my-page.service.ts
> Feat: 마이 페이지 초대 목록 api 추가

- src/controller/my-page.controller.ts
- src/dto/response/my-page/get-my-page-visible-profile.response.ts
- src/repository/my-page.query-repository.ts
- src/service/my-page.service.ts
마이 페이지 프로필 공개 여부 get api 추가
1분
> Feat: 마이 페이지 프로필 공개 여부 get api 추가

- src/controller/my-page.controller.ts
- src/dto/request/my-page/patch-my-page-visible-profile.ts
- src/entity/member.entity.ts
- src/service/my-page.service.ts
마이 페이지 유저 프로필 공개 여부 patch api 추가
1분
> Feat: 마이 페이지 유저 프로필 공개 여부 patch api 추가

- src/controller/post-detail.controller.ts
- src/dto/get-post-detail.dto.ts
- src/dto/response/post-detail.response.ts
- src/repository/post-detail.query-repository.ts
- src/service/post-detail.service.ts
> 포스트 상세 조회수, 댓글 수 올라가게 수정

- src/dto/get-post-detail.dto.ts
- src/dto/response/post-detail.response.ts
- src/entity/common/Enums.ts
- src/service/post-detail.service.ts
> 포스트 상세 userStatus 생성

- package-lock.json
- package.json
- src/app.module.ts
- src/controller/image.controller.ts
- src/dto/response/image.response.ts
- src/service/image.service.ts
이미지 업로드 url 생성 api
1분
아래와 같은 url이 나오면 해당 url로 PUT API 요청해서 이미지 업로드 처리하면 됩니다.
> Feat: 이미지 업로드 url 생성 api

- src/app.module.ts
- src/dto/response/my-page/get-my-page-invite.response.ts
- src/repository/my-page.query-repository.ts
팀 초대된 목록에 team_invite_id도 내려가게 수정
1분
> Feat: 팀 초대된 목록에 team_invite_id도 내려가게 수정

- src/app.module.ts
- src/controller/team.controller.ts
- src/dto/response/team/get-team-invite-info.response.ts
- src/repository/my-page.query-repository.ts
- src/repository/team-invite.query-repository.ts
- src/service/team.service.ts
> Feat: 팀 초대 조회 api

- src/controller/my-page.controller.ts
- src/entity/member.entity.ts
- src/service/my-page.service.ts
> Feat: 회원 탈퇴 api 추가

- src/controller/post-management.controller.ts
- src/entity/post.entity.ts
- src/service/post-management.service.ts
스터디 모집 상태 변경 관련 api를 시작, 완료 api로 변경
1분
> Feat: 스터디 모집 상태 변경 관련 api를 시작, 완료 api로 변경

- src/app.module.ts
- src/controller/member.controller.ts
- src/dto/request/search-member.request.ts
- src/dto/response/search-member.response.ts
- src/dto/search-member.dto.ts
- src/repository/member-search.query-repository.ts
- src/service/member-search.service.ts
> Feat: 유저 검색 api 추가

- src/dto/get-post-management.dto.ts
- src/dto/response/post-management.response.ts
> Feat: 스터디 정보에 stack 추가

- src/dto/get-post-management.dto.ts
- src/dto/response/post-management.response.ts
> Feat: 스터디 관리 상세, stack 배열 형태로 변경

- src/dto/get-post-management.dto.ts
- src/dto/response/post-management.response.ts
post management에 recuritEndAt, progressPeriod 추가
1분
> Feat: post management에 recuritEndAt, progressPeriod 추가

- src/app.module.ts
- src/controller/my-page.controller.ts
- src/controller/post.controller.ts
- src/service/post.service.ts
> Feat: scrap 추가 / 삭제 api

- src/controller/post-list.controller.ts
- src/dto/get-post-list.dto.ts
- src/dto/request/search-post-list.request.ts
- src/dto/response/post-list-response.ts
- src/entity/common/Enums.ts
- src/repository/post-list.query-repository.ts
- src/service/post-list.service.ts
스터디 목록 API를 수정했습니다.
5분
페이지네이션 객체 추가, isScraped 튜플 추가, 필터링이 추가되었습니다.
> 스터디 목록 API 수정

- src/controller/post-list.controller.ts
- src/dto/request/get-main-page.dto.ts
- src/dto/response/main-page.response.ts
- src/repository/post-list.query-repository.ts
- src/service/post-list.service.ts
메인 페이지 API를 추가했습니다.
5분
최신스터디, 인기스터디, 최신플젝, 인기플젝 리스트를 4개씩 불러왔습니다.
인기 기준은 (조회수, 스크랩 수) 순입니다.
> 메인 페이지 API 추가

- src/controller/post-detail.controller.ts
- src/dto/get-post-comment.dto.ts
- src/dto/get-post-detail.dto.ts
- src/dto/response/post-comment.response.ts
- src/dto/response/post-detail.response.ts
- src/repository/post-detail.query-repository.ts
스터디 상세 api를 수정했습니다.
1분
스터디 상세에서 memberId를, 스터디 댓글 목록에서 commentMemberId를 추가하였습니다.
> 스터디 상세 api 수정

- src/app.module.ts
- src/controller/my-post-controller.ts
- src/repository/post-list.query-repository.ts
- src/service/post-list.service.ts
내가 신청한 스터디 목록 API를 추가하였습니다
3분
[내가 신청한 스터디 목록 = 내가 초대받지 않고 직접 신청한 목록]으로만 일단 쿼리 작성하였습니다.
> 내가 신청한 스터디 목록 API

- src/controller/post-detail.controller.ts
- src/service/post-detail.service.ts
스터디 지원 취소 api를 추가하였습니다.
1분
팀 멤버에서 postId, memberId, status===READY 일 때 하드딜리트하였습니다.
> 스터디 지원 취소 api

- src/app.module.ts
- src/controller/scout.controller.ts
- src/dto/get-scout-post.dto.ts
- src/dto/request/scout-invite.request.ts
- src/dto/response/get-scout-post.response.ts
- src/entity/team-invite.entity.ts
- src/entity/team-member.entity.ts
- src/repository/scout.query-repository.ts
- src/service/scout.service.ts
스카웃 게시글, 초대하기 api 추가
3분
- 스카우트를 위한 현재 초대 가능한 스터디/프로젝트 목록 api
- 스터디/프로젝트 초대하기 api
> Feat: 스카웃 게시글, 초대하기 api 추가

- src/dto/request/search-post-list.request.ts
> search 타입 변경

- src/service/post-detail.service.ts
댓글 삭제 시, commentCount -1 감소하게 만들었습니다.
> 댓글 삭제 시, commentCount 감소하도록 기능 추가

- src/service/post-management.service.ts
스터디 완료 api, PROGRESS_END 상태로 바꾸도록 수정
1분
> Fix: 스터디 완료 api, PROGRESS_END 상태로 바꾸도록 수정

- src/dto/get-post-management.dto.ts
- src/dto/response/post-management.response.ts
- positions에 json parse 적용 안되어 있어서 수정
- post management api에 link 추가
1분
> FIx: positions에 json parse 적용 안되어 있어서 수정, post management api에 link 추가

- src/controller/post-management.controller.ts
- src/dto/get-post-team-member.dto.ts
- src/dto/response/post-team-member.response.ts
- src/service/post-management.service.ts
- src/service/post-team-member.service.ts
- 본인 인증 정보로 isLeader 판별하도록 처리
- 스터디 멤버 목록 api에서 글 작성자는 목록에 안나와서 나오도록 처리
2분
> Fix: 본인 인증 정보로 isLeader 판별하도록 처리, 스터디 멤버 목록 api에서 글 작성자는 목록에 안나와서 나오도록 처리

- src/repository/member-search.query-repository.ts
> Fix: 닉네임 검색, 앞뒤로 검색 다 되도록 처리

- src/repository/member-search.query-repository.ts
프로필 허용된 유저만 검색에 노출되도록 수정
stack 검색 제대로 안되는 버그 수정
1분
> Fix: 프로필 허용된 유저만 검색에 노출되도록 수정, stack 검색 제대로 안되는 버그 수정

- src/controller/member.controller.ts
- src/repository/member-search.query-repository.ts
- src/service/member-search.service.ts
유저 검색, 본인은 나오지 않도록 처리, anyone 제거
1분
> Fix: 유저 검색, 본인은 나오지 않도록 처리, anyone 제거

- src/main.ts
redis password
1분
redis password 추가
> Fix: redis password

- src/repository/post-list.query-repository.ts
> 스터디 목록 api 정렬 기준 수정

- src/controller/google-auth.controller.ts
- src/controller/member.controller.ts
- src/controller/my-page.controller.ts
- src/entity/member.entity.ts
- src/guard/roles.guard.ts
- src/main.ts
- src/repository/member.query-repository.ts
- src/service/google-authentication.service.ts
- src/service/my-page.service.ts
- src/service/session-serializer.service.ts
회원탈퇴한 사람은 걸러지게 수정 / 회원탈퇴 시 externalId 제거 / 로그아웃 api 추가
3분
> 회원 탈퇴한 사람은 걸러지게 수정 / 회원탈퇴 시 externalId 제거 / 로그아웃 api 추가

- src/dto/member.dto.ts
- src/dto/response/member/get-member.response.ts
- src/entity/member.entity.ts
member profile api에 isVisibleProfile 필드 추가
1분
> Feat: member profile api에 isVisibleProfile 필드 추가

- package-lock.json
- package.json
- src/app.module.ts
- src/controller/github-auth.controller.ts
- src/controller/google-auth.controller.ts
- src/guard/github-auth.guard.ts
- src/service/github-authentication.service.ts
- src/strategy/github-strategy.ts
> Feat: 깃헙 오어스 구현

- src/entity/team-invite.entity.ts
- src/service/scout.service.ts
- src/service/session-serializer.service.ts
team invite 생성 이상하게 되는 버그 수정
1분
> Fix: team invite 생성 이상하게 되는 버그 수정

- src/repository/member-search.query-repository.ts
멤버 프로필 api에서 탈퇴한 멤버는 안나오도록 수정
1분
> Fix: 멤버 프로필 api에서 탈퇴한 멤버는 안나오도록 수정

- src/app.module.ts
- src/entity/member-review-comment-entity.ts
> 멤버 리뷰 코멘트 엔티티 추가

- src/controller/post-detail.controller.ts
- src/service/post-detail.service.ts
조회수 증가 api 추가
1분
스터디 상세에서 조회수 증가시키던 것을 따로 API로 만들었습니다.
> 조회수 증가 api 추가

- src/app.module.ts
- src/controller/review.controller.ts
- src/dto/request/review/post-review.requset.ts
- src/service/review.service.ts
> Feat: 리뷰 작성 api 추가

- src/controller/post-management.controller.ts
- src/entity/post.entity.ts
- src/service/post-management.service.ts
> Feat: 스터디 리뷰 마감하는 api 추가, 권한 처리

- src/repository/post-list.query-repository.ts
On-going postList join을 inner에서 left로 수정했습니다.
1분
> On-going postList join방법 수정

- src/repository/post-list.query-repository.ts
검색 필터링 시 완료된 스터디가 나오는 문제 해결
1분
> 검색 필터링시 다른 조건이 나오는 오류 해결

- src/repository/post-list.query-repository.ts
> 나의 스터디 카운트 잘못 받아오던 것 수정

- src/controller/member.controller.ts
- src/dto/member.dto.ts
- src/dto/response/member/get-member.response.ts
- src/service/member.service.ts
member profile api에 isMine 필드 추가
1분
> Feat: member profile api에 isMine 필드 추가

- src/dto/response/team/get-team-invite-info.response.ts
- src/repository/team-invite.query-repository.ts
- src/service/team.service.ts
team invite api에 sendMemberProfileImageUrl 추가
1분
> Feat: team invite api에 sendMemberProfileImageUrl 추가

- src/repository/scout.query-repository.ts
scout post api, ready 상태만 내려가도록 수정
1분
> Fix: scout post api, ready 상태만 내려가도록 수정

- src/controller/my-page.controller.ts
- src/dto/response/my-page/get-my-page-review.response.ts
- src/repository/my-page.query-repository.ts
- src/service/my-page.service.ts
> Feat: 내가 받은 리뷰 목록 api 추가

- src/entity/team-member.entity.ts
- src/service/post-team-member.service.ts
초대된 팀원 삭제 시 변경 사항이 추가되었습니다.
1분
READY, SELF로 바꾸고, teamInviteId가 있다면 지워주는 것으로 변경했습니다.
해당 teamInviteId의 레코드를 삭제하였습니다.
> 초대된 팀원 삭제 시 변경사항 추가

- src/dto/get-post-complete.dto.ts
- src/dto/response/post-complete-list.response.ts
- src/repository/post-list.query-repository.ts
내가 완료한 스터디에 isReviewed 추가했습니다.
1분
> 내가 완료한 스터디에 isReviewed 추가

- src/repository/team-member.query-repository.ts
- src/service/post-management.service.ts
> Feat: 초대받은 사람은 신청자 목록에 안나오록 처리

- src/repository/post-list.query-repository.ts
> 나의 대기중인 스터디 쿼리 로직 변경

- src/repository/team-member.query-repository.ts
- src/service/post-detail.service.ts
포스트의 주인이 탈퇴된 멤버일 때, 예외 처리를 추가했습니다.
1분
스터디 지원 API, 현재 팀원 불러오기 API
> 탈퇴된 멤버 로직 수정

- src/repository/scout.query-repository.ts
스카우트 목록에서 회원탈퇴 예외처리를 추가했습니다
1분
> 스카우트 목록 회원탈퇴 예외처리 추가

- src/controller/review.controller.ts
- src/dto/member.dto.ts
- src/dto/response/my-page/get-my-page-info.response.ts
- src/dto/search-member.dto.ts
- src/repository/member-search.query-repository.ts
- src/repository/my-page.query-repository.ts
- src/service/member.service.ts
- src/service/my-page.service.ts
마이 페이지 유저 정보, 유저 검색, 유저 프로필 조회 gauge 값 추가 / 맴버별 리뷰 조회 api 추가
3분
> 마이 페이지 유저 정보, 유저 검색, 유저 프로필 조회 gauge 값 추가 / 맴버별 리뷰 조회 api 추가

- src/dto/response/review/get-review-member.response.ts
- src/repository/team-member.query-repository.ts
- src/service/review.service.ts
리뷰 멤버 조회시, 방장도 조회되도록 변경했습니다.
1분
push를 사용했습니다.
> 리뷰 멤버 조회시, 방장도 조회되도록 변경

- src/dto/get-post-management.dto.ts
- src/dto/response/post-management.response.ts
- src/service/post-management.service.ts
post management 조회 시, isReviewed도 같이 내려주었습니다.
1분
> post management 조회 시, isReviewed도 같이 내려줌

- src/controller/review.controller.ts
- src/dto/request/review/post-review.requset.ts
- src/entity/member-review-comment-entity.ts
- src/service/review.service.ts
리뷰 작성 안되던 것 수정하였습니다.
1분
memberReviewComment의 content가 comment로 변경되었습니다.
> 리뷰 작성 안되던 것 수정

- src/service/review.service.ts
접속멤버가 방장일 때, 에러뜨는 것을 수정하였습니다.
1분
> 리뷰 팀멤버 조회 수정

- src/app.module.ts
- src/calculator/review-score.calculator.spec.ts
- src/calculator/review-score.calculator.ts
- src/repository/post-count.query-repository.ts
- src/service/post-management.service.ts
스터디 리뷰 점수 계산, 완료 스터디 갯수로 가중치 계산하도록 수정
1분
> Feat: 스터디 리뷰 점수 계산, 완료 스터디 갯수로 가중치 계산하도록 수정

- src/controller/review.controller.ts
> 유저 리뷰 목록 엔드포인트 변경

- src/calculator/review-score.calculator.spec.ts
- src/calculator/review-score.calculator.ts
리뷰시 완료 스터디 갯수가 0으로 시작하면 무한대 값으로 나와서 예외처리
1분
> Fix: 리뷰시 완료 스터디 갯수가 0으로 시작하면 무한대 값으로 나와서 예외처리

- src/service/post-management.service.ts
> Fix: 방장의 리뷰 점수는 반영되지 않는 문제 수정
